drop table if exists employee;
CREATE TABLE employee (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 0) PRIMARY KEY,
  firstname   VARCHAR(64) NOT NULL,
  lastname    VARCHAR(64) NOT NULL,
  age         INTEGER NOT NULL
  );
